from __future__ import annotations

"""
Database action layer for the PG FAQ feature.

This file answers: "What database operations can the rest of the app perform?"

The FastAPI routes in `main.py` and the bootstrap flow in `embed.py` should call
these named functions instead of writing database queries inline. That keeps
HTTP logic, bootstrap orchestration, and database behavior separated.

The functions here use SQLAlchemy ORM/expression APIs against the `Faq` model:
- direct lookup by id
- semantic search by pgvector cosine distance
- replace all seeded FAQ rows
- find/update missing embeddings
- count rows for bootstrap logs

Return values are small dataclasses rather than raw ORM objects so callers do
not depend on SQLAlchemy session-bound model instances.
"""

from dataclasses import dataclass
from typing import Optional, Sequence

from sqlalchemy import delete, func, select
from sqlalchemy.orm import Session

from pg.faq_api.orm import Faq


@dataclass(frozen=True)
class FaqSearchRow:
    """FAQ row returned by lookup/search operations."""

    id: int
    question: str
    answer: str
    cosine_similarity: float


@dataclass(frozen=True)
class FaqEmbeddingInput:
    """FAQ row that needs an embedding backfill."""

    id: int
    question: str


def _to_search_row(faq: Faq, cosine_similarity: float) -> FaqSearchRow:
    return FaqSearchRow(
        id=int(faq.id),
        question=faq.question,
        answer=faq.answer,
        cosine_similarity=float(cosine_similarity),
    )


def get_faq_by_id(session: Session, faq_id: int) -> Optional[FaqSearchRow]:
    """Fetch one FAQ by id for direct UI clickthrough."""

    faq = session.get(Faq, faq_id)
    if faq is None:
        return None
    return _to_search_row(faq, 1.0)


def search_faqs_by_embedding(
    session: Session,
    query_embedding: Sequence[float],
    limit: int,
) -> list[FaqSearchRow]:
    """Find semantically similar FAQs by computing pgvector cosine distance.
    
     Computes cosine distance between the query embedding and all FAQ embeddings in the database. Returns the top-k most similar FAQs ordered by similarity (highest first).
    
    Args:
        session: SQLAlchemy session for database access
        query_embedding: Embedding vector of the user's question (1024 floats, e.g., [0.1, 0.2, 0.3, ...])
        limit: Maximum number of results to return (e.g., 5)
    
    Returns:
        list[FaqSearchRow]: Top-k FAQs with computed similarity scores (1.0 = identical, -1.0 = opposite)
    """

    distance = Faq.embedding.cosine_distance(list(query_embedding)) # distance is between 0 and 2, where 0 means identical and 1 means orthogonal, so we convert to similarity for easier UI display.
    cosine_similarity = (1 - distance).label("cosine_similarity") # similarity is between -1 and 1, where 1 means identical, 0 means orthogonal, and -1 means opposite.

    stmt = ( # 
        select(Faq, cosine_similarity)
        .where(Faq.embedding.is_not(None))
        .order_by(distance)
        .limit(limit)
    )

    results: list[FaqSearchRow] = []
    for faq, similarity in session.execute(stmt): # ← HERE! Query executes
    # Now distance is computed for each FAQ
    # Each row gets its own distance value
        results.append(_to_search_row(faq, similarity))
    return results


def replace_seed_faqs(session: Session, rows: Sequence[dict]) -> int:
    """Replace all FAQ rows with the seed FAQ rows."""

    session.execute(delete(Faq))

    session.add_all(
        Faq(
            question=row["question"],
            answer=row["answer"],
        )
        for row in rows
    )
    return len(rows)


def get_faqs_missing_embeddings(session: Session, limit: int) -> list[FaqEmbeddingInput]:
    """Return a deterministic batch of FAQ rows that still need embeddings."""

    stmt = (
        select(Faq.id, Faq.question)
        .where(Faq.embedding.is_(None))
        .order_by(Faq.id)
        .limit(limit)
    )
    return [FaqEmbeddingInput(id=int(row.id), question=row.question) for row in session.execute(stmt)]


def update_faq_embedding(session: Session, faq_id: int, embedding: Sequence[float]) -> None:
    """Assign a computed embedding vector to a specific FAQ row.
    
    Used by the bootstrap flow to backfill embeddings generated by Ollama.
    Silently returns if FAQ id does not exist (no error raised).
    
    Args:
        session: SQLAlchemy session for database access
        faq_id: The FAQ row to update
        embedding: The embedding vector from Ollama (1024 floats)
    """

    faq = session.get(Faq, faq_id)
    if faq is None:
        return
    faq.embedding = list(embedding)


def count_faqs(session: Session) -> int:
    """Count total FAQ rows in the database.
    
    Used by bootstrap logs to track initial FAQ load. Returns 0 if table is empty.
    
    Args:
        session: SQLAlchemy session for database access
    
    Returns:
        int: Total number of FAQ rows
    """

    return int(session.scalar(select(func.count()).select_from(Faq)) or 0)


def count_faqs_missing_embeddings(session: Session) -> int:
    """Count FAQ rows that lack embeddings (need backfill).
    
    Used by the bootstrap flow to determine how many FAQs still need Ollama embeddings.
    Returns 0 if all FAQs have embeddings.
    
    Args:
        session: SQLAlchemy session for database access
    
    Returns:
        int: Number of FAQ rows with `embedding IS NULL`
    """

    stmt = select(func.count()).select_from(Faq).where(Faq.embedding.is_(None))
    return int(session.scalar(stmt) or 0)
